### ISSUE TITLE
Project roadmap

### ISSUE THREAD

**Issue by kangarlou** [kubernetes-client/c#111]
Hello @ityuhui @brendandburns. NetApp is interested in a Kubernetes client library for C. The documentation is clear that the project "is a work in progress and should be considered alpha quality software at this time". As you know, there is only one tagged version for k8s 1.17 and HEAD supports k8s 1.22 with some support for the releases in between: https://github.com/kubernetes-client/c/blob/master/docs/versioning-and-compatibility.md#compatibility

1. Are there plans to have a tagged version/release for every minor k8s release going forward?
2. What are some of the major gaps that make this project alpha and what's the timeline to address them?

Thanks!
Ardalan

**Comment by ityuhui** [comment]
1. Version/release tags are on demand now. If someone needs it, we can bump into the latest stable version and tag the old code. For myself, I will tag every major release since k8s v1.22. I have no plans to tag every minor k8s release now. Hi @brendandburns what's your opinion about this?

2. I think the quality of this project can be considered [beta](https://github.com/kubernetes/design-proposals-archive/blob/main/api-machinery/csi-new-client-library-procedure.md#client-support-level) now but I haven't updated the readme.  The C client supports all [silver requirements](https://github.com/kubernetes/design-proposals-archive/blob/main/api-machinery/csi-new-client-library-procedure.md#client-capabilities) and some gold requirements e.g. exec, attach.

**Comment by brendandburns** [comment]
@kangarlou I think that anyone adopting this library should expect that they will need to help with some of the work on it. 

It is done (as is most OSS) by volunteer effort (mostly @ityuhui if I'm being honest).

It should work, and is mostly stable, but problems have been found in the past (e.g. memory leaks) and I imagine they will be found in the future.

Tagged release for every minor Kubernetes version sounds good, and we may do cherry-pick/patch releases if there are bugs

I think you can depend on this library, but you should expect that you may need to do some work. 

Plus, we'd love to have help!

**Comment by brendandburns** [comment]
I'm going to close this issue since I believe that the question is resolved (@kangarlou I hope you join us :)
