### ISSUE TITLE
some keywords conflict occurs with zebos

### ISSUE THREAD

**Issue by clearday4** [kubernetes-client/c#90]
If I link the libkubernetes and zebos together, some keywords conflict occurred.
list_create, list_free
could you change these keywords?

```
18:04:22,338 INFO  - //MW_LIB/KAS/obj/x86_K8.4/libkubernetes.a(list.c.o): In function `list_create':
18:04:22,338 INFO  - //MW_LIB/KAS/K8SCLIENT_C_3RD/kubernetes/src/list.c:26: multiple definition of `list_create'
18:04:22,338 INFO  - ../../platform/arch-x86_K/obj/lib.a(linklist.o)://NET_APP/ZEBOS/ZEBOS3RD/lib/linklist.c:21: first defined here
18:04:22,338 INFO  - //MW_LIB/KAS/obj/x86_K8.4/libkubernetes.a(list.c.o): In function `list_free':
18:04:22,338 INFO  - //MW_LIB/KAS/K8SCLIENT_C_3RD/kubernetes/src/list.c:92: multiple definition of `list_free'
18:04:22,338 INFO  - ../../platform/arch-x86_K/obj/lib.a(linklist.o)://NET_APP/ZEBOS/ZEBOS3RD/lib/linklist.c:48: first defined here
18:04:22,338 INFO  - collect2: error: ld returned 1 exit status
```

**Comment by ityuhui** [comment]
@minerba

Since your PR ( https://github.com/OpenAPITools/openapi-generator/pull/11190 and https://github.com/OpenAPITools/openapi-generator/pull/11677) have already been committed, can you regenerate the c client to merge the change? The guide can be found at  https://github.com/kubernetes-client/c/blob/master/docs/how-to-regenerate-the-c-client.md

**Comment by minerba** [comment]
@ityuhui  Ok, I will check

**Comment by ityuhui** [comment]
@minerba 

I merge your code by the PR #109 because I want to fix a bug based on the latest code.
So you don't need re-generate the C client any more for this ticket.
Thanks !

**Comment by minerba** [comment]
@ityuhui 
Ok, Thank you!
